# Generated by Django 5.0.6 on 2024-06-08 09:19

import messaging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_remove_textmessage_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='icon',
            field=models.ImageField(upload_to=messaging.models.get_image_upload_path_room),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_bg_image',
            field=models.ImageField(upload_to=messaging.models.get_image_upload_path_room),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(null=True, upload_to=messaging.models.get_image_upload_path_message),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.FileField(null=True, upload_to=messaging.models.get_video_upload_path_message),
        ),
    ]
