# Generated by Django 5.0.6 on 2024-07-07 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0004_pollmessage_polloption_pollingchoice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pollingchoice",
            old_name="user",
            new_name="voter",
        ),
    ]
