# Generated by Django 5.0.6 on 2024-07-13 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0039_delete_messagenotificationsetting"),
        ("messaging", "0005_rename_user_pollingchoice_voter"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageNotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allow_all", models.BooleanField(default=True)),
                ("replies_only", models.BooleanField(default=False)),
                ("mute_all", models.BooleanField(default=False)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="messaging.chatroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.userstats"
                    ),
                ),
            ],
        ),
    ]
