# Generated by Django 5.0.6 on 2024-08-07 22:47

import messaging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0008_alter_chatroom_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="audio",
            field=models.FileField(
                null=True, upload_to=messaging.models.get_audio_upload_path_message
            ),
        ),
    ]
