# Generated by Django 5.0.6 on 2024-08-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0009_message_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
