# Generated by Django 5.0.6 on 2024-08-24 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0039_delete_messagenotificationsetting"),
        ("messaging", "0011_reaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="messaging.message",
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="main.userstats",
            ),
        ),
    ]
