# Generated by Django 5.0.6 on 2025-01-09 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0014_alter_message_room"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reaction",
            old_name="created_at",
            new_name="date_created",
        ),
    ]
