import os

from messaging.models import ChatRoom
from main.models import UserStats

def get_chat_rooms(user):
    user_stats = UserStats.objects.get(user=user)
    chat_rooms = ChatRoom.objects.filter(users=user_stats)
    return chat_rooms


def replace_spaces(string, replacement):
    string_list = [char for char in string]
    for index, char in enumerate(string_list):
        if char == ' ':
            string_list[index] = str(replacement)
    new_string = ''
    for chars in string_list:
        new_string = new_string + chars

    return new_string

# define the changing of the username's directory (for neatness of code)
def change_user_directory(old_dir, new_dir):
    os.replace(old_dir, new_dir)

# Emoticon Dictionary
emoticons_dict = {
    "grinning_face": "&#x1F600;",
    "grinning_face_with_big_eyes": "&#x1F603;",
    "grinning_face_with_smiling_eyes": "&#x1F604;",
    "beaming_face_with_smiling_eyes": "&#x1F601;",
    "grinning_squinting_face": "&#x1F606;",
    "grinning_face_with_sweat": "&#x1F605;",
    "rolling_on_the_floor_laughing": "&#x1F923;",
    "face_with_tears_of_joy": "&#x1F602;",
    "slightly_smiling_face": "&#x1F642;",
    "upside_down_face": "&#x1F643;",
    "winking_face": "&#x1F609;",
    "smiling_face_with_smiling_eyes": "&#x1F60A;",
    "smiling_face_with_halo": "&#x1F607;",
    "smiling_face_with_hearts": "&#x1F970;",
    "smiling_face_with_heart_eyes": "&#x1F60D;",
    "star_struck": "&#x1F929;",
    "face_blowing_a_kiss": "&#x1F618;",
    "kissing_face": "&#x1F617;",
    "smiling_face": "&#x263A;",
    "kissing_face_with_closed_eyes": "&#x1F61A;",
    "kissing_face_with_smiling_eyes": "&#x1F619;",
    "face_savoring_food": "&#x1F60B;",
    "face_with_tongue": "&#x1F61B;",
    "winking_face_with_tongue": "&#x1F61C;",
    "zany_face": "&#x1F92A;",
    "squinting_face_with_tongue": "&#x1F61D;",
    "money_mouth_face": "&#x1F911;",
    "hugging_face": "&#x1F917;",
    "face_with_hand_over_mouth": "&#x1F92D;",
    "shushing_face": "&#x1F92B;",
    "thinking_face": "&#x1F914;",
    "zipper_mouth_face": "&#x1F910;",
    "face_with_raised_eyebrow": "&#x1F928;",
    "neutral_face": "&#x1F610;",
    "expressionless_face": "&#x1F611;",
    "face_without_mouth": "&#x1F636;",
    "smirking_face": "&#x1F60F;",
    "unamused_face": "&#x1F612;",
    "face_with_rolling_eyes": "&#x1F644;",
    "grimacing_face": "&#x1F62C;",
    "lying_face": "&#x1F925;",
    "relieved_face": "&#x1F60C;",
    "pensive_face": "&#x1F614;",
    "sleepy_face": "&#x1F62A;",
    "drooling_face": "&#x1F924;",
    "sleeping_face": "&#x1F634;",
    "face_with_medical_mask": "&#x1F637;",
    "face_with_thermometer": "&#x1F912;",
    "face_with_head_bandage": "&#x1F915;",
    "nauseated_face": "&#x1F922;",
    "face_vomiting": "&#x1F92E;",
    "sneezing_face": "&#x1F927;",
    "hot_face": "&#x1F975;",
    "cold_face": "&#x1F976;",
    "woozy_face": "&#x1F974;",
    "dizzy_face": "&#x1F635;",
    "exploding_head": "&#x1F92F;",
    "cowboy_hat_face": "&#x1F920;",
    "partying_face": "&#x1F973;",
    "disguised_face": "&#x1F978;",
    "smiling_face_with_sunglasses": "&#x1F60E;",
    "nerd_face": "&#x1F913;",
    "face_with_monocle": "&#x1F9D0;",
    "confused_face": "&#x1F615;",
    "worried_face": "&#x1F61F;",
    "slightly_frowning_face": "&#x1F641;",
    "frowning_face": "&#x2639;",
    "face_with_open_mouth": "&#x1F62E;",
    "hushed_face": "&#x1F62F;",
    "astonished_face": "&#x1F632;",
    "flushed_face": "&#x1F633;",
    "pleading_face": "&#x1F97A;",
    "frowning_face_with_open_mouth": "&#x1F626;",
    "anguished_face": "&#x1F627;",
    "fearful_face": "&#x1F628;",
    "anxious_face_with_sweat": "&#x1F630;",
    "sad_but_relieved_face": "&#x1F625;",
    "crying_face": "&#x1F622;",
    "loudly_crying_face": "&#x1F62D;",
    "face_screaming_in_fear": "&#x1F631;",
    "confounded_face": "&#x1F616;",
    "persevering_face": "&#x1F623;",
    "disappointed_face": "&#x1F61E;",
    "downcast_face_with_sweat": "&#x1F613;",
    "weary_face": "&#x1F629;",
    "tired_face": "&#x1F62B;",
    "yawning_face": "&#x1F971;",
    "face_with_steam_from_nose": "&#x1F624;",
    "pouting_face": "&#x1F621;",
    "angry_face": "&#x1F620;",
    "face_with_symbols_on_mouth": "&#x1F92C;",
    "smiling_face_with_horns": "&#x1F608;",
    "angry_face_with_horns": "&#x1F47F;",
    "skull": "&#x1F480;",
    "skull_and_crossbones": "&#x2620;",
    "pile_of_poo": "&#x1F4A9;",
    "clown_face": "&#x1F921;",
    "ogre": "&#x1F479;",
    "goblin": "&#x1F47A;",
    "ghost": "&#x1F47B;",
    "alien": "&#x1F47D;",
    "alien_monster": "&#x1F47E;",
    "robot": "&#x1F916;",
    "grinning_cat": "&#x1F63A;",
    "grinning_cat_with_smiling_eyes": "&#x1F638;",
    "cat_with_tears_of_joy": "&#x1F639;",
    "smiling_cat_with_heart_eyes": "&#x1F63B;",
    "cat_with_wry_smile": "&#x1F63C;",
    "kissing_cat": "&#x1F63D;",
    "weary_cat": "&#x1F640;",
    "crying_cat": "&#x1F63F;",
    "pouting_cat": "&#x1F63E;",
    "see_no_evil_monkey": "&#x1F648;",
    "hear_no_evil_monkey": "&#x1F649;",
    "speak_no_evil_monkey": "&#x1F64A;",
    "kiss_mark": "&#x1F48B;",
    "love_letter": "&#x1F48C;",
    "heart_with_arrow": "&#x1F498;",
    "heart_with_ribbon": "&#x1F49D;",
    "sparkling_heart": "&#x1F496;",
    "growing_heart": "&#x1F497;",
    "beating_heart": "&#x1F493;",
    "revolving_hearts": "&#x1F49E;",
    "two_hearts": "&#x1F495;",
    "heart_decoration": "&#x1F49F;",
    "heart_exclamation": "&#x2763;",
    "broken_heart": "&#x1F494;",
    "red_heart": "&#x2764;",
    "orange_heart": "&#x1F9E1;",
    "yellow_heart": "&#x1F49B;",
    "green_heart": "&#x1F49A;",
    "blue_heart": "&#x1F499;",
    "purple_heart": "&#x1F49C;",
    "brown_heart": "&#x1F90E;",
    "black_heart": "&#x1F5A4;",
    "white_heart": "&#x1F90D;",
    "hundred_points": "&#x1F4AF;",
    "anger_symbol": "&#x1F4A2;",
    "collision": "&#x1F4A5;",
    "dizzy": "&#x1F4AB;",
    "sweat_droplets": "&#x1F4A6;",
    "dashing_away": "&#x1F4A8;",
    "hole": "&#x1F573;",
    "bomb": "&#x1F4A3;",
    "speech_balloon": "&#x1F4AC;",
    "eye_in_speech_bubble": "&#x1F441;&#xFE0F;&#x200D;&#x1F5E8;&#xFE0F;",
    "left_speech_bubble": "&#x1F5E8;",
    "right_anger_bubble": "&#x1F5EF;",
    "thought_balloon": "&#x1F4AD;",
    "zzz": "&#x1F4A4;"
}
