# Generated by Django 5.0.2 on 2024-04-09 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_post_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="media_mp3",
            new_name="media",
        ),
    ]
