# Generated by Django 5.0.3 on 2024-04-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_rename_media_mp3_post_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date_modified",
            field=models.DateTimeField(null=True),
        ),
    ]
