# Generated by Django 5.0.2 on 2024-04-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_post_date_modified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="user_pfp",
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
