# Generated by Django 5.0.2 on 2024-04-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_remove_post_user_pfp_alter_post_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_modified",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
