# Generated by Django 5.0.2 on 2024-04-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_comment_nestedcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="liked_by",
            field=models.ManyToManyField(to="main.likedby"),
        ),
        migrations.AddField(
            model_name="nestedcomment",
            name="liked_by",
            field=models.ManyToManyField(to="main.likedby"),
        ),
    ]
