# Generated by Django 5.0.3 on 2024-04-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_interest_posttag"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
