# Generated by Django 5.0.2 on 2024-05-11 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_delete_alltag_interest_current_increace_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ICF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form", models.CharField(max_length=100)),
                ("a", models.IntegerField()),
                ("k", models.IntegerField()),
                (
                    "interest",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="main.interest"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PCF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form", models.CharField(max_length=100)),
                ("a", models.IntegerField()),
                ("k", models.IntegerField()),
                (
                    "tag",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="main.posttag"
                    ),
                ),
            ],
        ),
    ]
