# Generated by Django 5.0.2 on 2024-05-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_icf_pcf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="icf",
            name="a",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="icf",
            name="k",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="pcf",
            name="a",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="pcf",
            name="k",
            field=models.FloatField(),
        ),
    ]
