# Generated by Django 5.0.2 on 2024-05-18 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_alter_interest_date_of_change_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interest",
            name="current_increace",
        ),
        migrations.RemoveField(
            model_name="interest",
            name="date_of_change",
        ),
        migrations.RemoveField(
            model_name="interest",
            name="previous_increace",
        ),
        migrations.RemoveField(
            model_name="posttag",
            name="current_increace",
        ),
        migrations.RemoveField(
            model_name="posttag",
            name="date_of_change",
        ),
        migrations.RemoveField(
            model_name="posttag",
            name="previous_increace",
        ),
        migrations.CreateModel(
            name="InterestInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
                ("type", models.CharField(max_length=20)),
                (
                    "interest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.interest"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
                ("type", models.CharField(max_length=20)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.post"
                    ),
                ),
            ],
        ),
    ]
