# Generated by Django 5.0.2 on 2024-05-19 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_remove_interest_current_increace_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DaySave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object", models.CharField(max_length=300)),
                ("key", models.IntegerField()),
                ("day", models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name="postinteraction",
            name="post",
        ),
        migrations.AddField(
            model_name="postinteraction",
            name="tag",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.posttag",
            ),
            preserve_default=False,
        ),
    ]
