# Generated by Django 5.0.2 on 2024-05-19 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("main", "0017_daysave_remove_postinteraction_post_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daysave",
            name="key",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="daysave",
            name="object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
