# Generated by Django 5.0.2 on 2024-05-19 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("main", "0018_alter_daysave_key_alter_daysave_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="DateAndOrTimeSave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abstract", models.CharField(max_length=300, null=True)),
                ("key", models.PositiveIntegerField(null=True)),
                ("day", models.DateField(null=True)),
                ("time", models.TimeField(null=True)),
                ("day_time", models.DateTimeField(null=True)),
                (
                    "object",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DaySave",
        ),
    ]
