# Generated by Django 5.0.2 on 2024-05-19 04:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_dateandortimesave_delete_daysave"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dateandortimesave",
            name="key",
        ),
    ]
