# Generated by Django 5.0.3 on 2024-05-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_remove_dateandortimesave_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstats",
            name="last_recorded_latitude",
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userstats",
            name="last_recorded_longitude",
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="icf",
            name="a",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="icf",
            name="k",
            field=models.FloatField(null=True),
        ),
    ]
