# Generated by Django 5.0.2 on 2024-05-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_userstats_last_recorded_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstats",
            name="time_of_recorded_location",
            field=models.DateTimeField(null=True),
        ),
    ]
