# Generated by Django 5.0.2 on 2024-05-27 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_userstats_time_of_recorded_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userstats",
            old_name="time_of_recorded_location",
            new_name="last_recorded_location",
        ),
    ]
