# Generated by Django 5.0.2 on 2024-05-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "main",
            "0023_rename_time_of_recorded_location_userstats_last_recorded_location",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstats",
            name="last_recorded_location",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
