# Generated by Django 5.0.2 on 2024-05-27 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0024_alter_userstats_last_recorded_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstats",
            name="last_recorded_location",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2024, 5, 28, 6, 11, 38, 886805),
            ),
            preserve_default=False,
        ),
    ]
