# Generated by Django 5.0.2 on 2024-05-31 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0025_alter_userstats_last_recorded_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="day_of_creation",
            field=models.DateField(default=datetime.date(2024, 5, 31)),
            preserve_default=False,
        ),
    ]
