# Generated by Django 5.0.6 on 2024-06-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_post_day_of_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='can_comment',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstats',
            name='can_post',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstats',
            name='is_banned',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
