# Generated by Django 5.0.6 on 2024-06-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_userstats_can_comment_userstats_can_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='can_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='can_post',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
