# Generated by Django 5.0.6 on 2024-06-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_userstats_last_recorded_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArabaliConfigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('can_sign_up', models.BooleanField(default=True)),
            ],
        ),
    ]
