# Generated by Django 5.0.6 on 2024-06-25 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0035_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
