# Generated by Django 5.0.6 on 2024-07-10 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0037_remove_notification_type_and_more"),
        ("messaging", "0005_rename_user_pollingchoice_voter"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="relevant_poll",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="messaging.pollmessage",
            ),
        ),
    ]
