# Generated by Django 5.0.6 on 2024-11-19 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0039_delete_messagenotificationsetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nestedcomment",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="main.comment",
            ),
        ),
    ]
