# Generated by Django 5.0.6 on 2024-11-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0040_alter_nestedcomment_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="liked_by",
            field=models.ManyToManyField(
                related_name="comment_liked_by", to="main.likedby"
            ),
        ),
        migrations.AlterField(
            model_name="nestedcomment",
            name="liked_by",
            field=models.ManyToManyField(
                related_name="reply_liked_by", to="main.likedby"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="liked_by",
            field=models.ManyToManyField(
                related_name="post_liked_by", to="main.likedby"
            ),
        ),
    ]
