# Generated by Django 5.0.6 on 2024-11-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0043_remove_post_media_alter_post_title_media"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="day_of_creation",
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
