# Generated by Django 5.0.6 on 2024-11-24 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0044_remove_post_day_of_creation_alter_post_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="main.post",
            ),
        ),
    ]
