# Generated by Django 5.0.6 on 2024-11-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0045_alter_media_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Catergory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
