# Generated by Django 5.0.6 on 2024-11-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0046_catergory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pcf",
            old_name="a",
            new_name="factor",
        ),
        migrations.RemoveField(
            model_name="icf",
            name="a",
        ),
        migrations.RemoveField(
            model_name="icf",
            name="form",
        ),
        migrations.RemoveField(
            model_name="icf",
            name="k",
        ),
        migrations.RemoveField(
            model_name="interestinteraction",
            name="type",
        ),
        migrations.RemoveField(
            model_name="pcf",
            name="form",
        ),
        migrations.RemoveField(
            model_name="pcf",
            name="k",
        ),
        migrations.RemoveField(
            model_name="postinteraction",
            name="type",
        ),
        migrations.AddField(
            model_name="icf",
            name="factor",
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interestinteraction",
            name="is_new",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pcf",
            name="is_active",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="postinteraction",
            name="is_new",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
