# Generated by Django 5.0.6 on 2024-12-19 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0047_rename_a_pcf_factor_remove_icf_a_remove_icf_form_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="media",
            old_name="caption",
            new_name="caption_text",
        ),
        migrations.AddField(
            model_name="media",
            name="caption_colour",
            field=models.CharField(default="#ffffffff", max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="media",
            name="caption_font",
            field=models.CharField(default="default", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="icf",
            name="interest",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ICF",
                to="main.interest",
            ),
        ),
        migrations.AlterField(
            model_name="interest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="interestinteraction",
            name="interest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interest_interactions",
                to="main.interest",
            ),
        ),
        migrations.AlterField(
            model_name="pcf",
            name="tag",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="PCF",
                to="main.posttag",
            ),
        ),
        migrations.AlterField(
            model_name="postinteraction",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_interactions",
                to="main.posttag",
            ),
        ),
        migrations.AlterField(
            model_name="posttag",
            name="post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_tag",
                to="main.post",
            ),
        ),
    ]
