# Generated by Django 5.0.6 on 2025-01-08 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0048_rename_caption_media_caption_text_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Catergory",
            new_name="Category",
        ),
    ]
