# Generated by Django 5.0.6 on 2025-01-09 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0050_rename_created_at_post_date_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="created_at",
            new_name="date_created",
        ),
        migrations.RenameField(
            model_name="nestedcomment",
            old_name="created_at",
            new_name="date_created",
        ),
    ]
