# Generated by Django 5.0.6 on 2025-01-31 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0051_rename_created_at_comment_date_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pcf",
            name="is_active",
        ),
    ]
